Update Ansible PostgreSQL role to latest

diff --git a/pouta-env/roles/3rdparty/postgresql/templates/scheduled_backup.sh.j2 b/pouta-env/roles/3rdparty/postgresql/templates/scheduled_backup.sh.j2
--- a/pouta-env/roles/3rdparty/postgresql/templates/scheduled_backup.sh.j2
+++ b/pouta-env/roles/3rdparty/postgresql/templates/scheduled_backup.sh.j2
@@ -5,19 +5,20 @@
 
 server=`hostname`
 data='{{ postgresql_pgdata }}'
-dir="{{ postgresql_backup_dir }}/$server/current"
-old="{{ postgresql_backup_dir }}/$server/previous"
-older="{{ postgresql_backup_dir }}/$server/older"
+dir='{{ postgresql_backup_dir }}/current'
 mailto='{{ postgresql_backup_mail_recipient }}'
-mutex="{{ postgresql_backup_local_dir }}/nightlymutex"
+mutex='{{ postgresql_backup_local_dir }}/scheduledmutex'
+rotate='{{ postgresql_backup_rotate | default("True") }}'
+
+[ '{{ postgresql_backup_remote_rsync_path | default("None") }}' != 'None' ] && remote_rsync='--rsync-path={{ postgresql_backup_remote_rsync_path }}' || remote_rsync=''
 
 handler()
 {
     command=$@
     out=`$command 2>&1`
     ret=$?
-    if [ $ret != 0 ]; then
-        (echo "execuing $command failed with code $ret:" ; echo "$out") | mail -s "$server: Postgres nightly backup failed" $mailto
+    if [ $ret -ne 0 -a ! \( $ret -eq 24 -a $1 = 'rsync' \) ]; then
+        (echo "execuing $command failed with code $ret:" ; echo "$out") | mail -s "$server: Postgres scheduled backup failed" $mailto
         rm -f $mutex
         if [ "$backup_started" = 1 ]; then
             echo "SELECT pg_stop_backup();" | psql
@@ -35,15 +36,15 @@ psql_handler()
     sql=$@
     out=`echo "$sql" | psql 2>&1`
     ret=$?
-    if [ $ret != 0 ]; then
-        (echo "executing $sql failed with code $ret:" ; echo "$out") | mail -s "$server: Postgres nightly backup failed" $mailto
+    if [ $ret -ne 0 ]; then
+        (echo "executing $sql failed with code $ret:" ; echo "$out") | mail -s "$server: Postgres scheduled backup failed" $mailto
         rm -f $mutex
         exit 1
     else
         probe=`echo "$out" | grep ERROR`
         ret=$?
-        if [ $ret = 0 ]; then
-            (echo "executing sql $sql failed:" ; echo "$out") | mail -s "$server: Postgres nightly backup failed" $mailto
+        if [ $ret -eq 0 ]; then
+            (echo "executing sql $sql failed:" ; echo "$out") | mail -s "$server: Postgres scheduled backup failed" $mailto
             rm -f $mutex
             exit 1
         #else
@@ -54,6 +55,9 @@ psql_handler()
     fi
 }
 
+[[ "$dir" == *':'* ]] && dir_is_remote=1
+[ "$dir_is_remote" -a $rotate != "False" ] && { echo "error: rotation with remote backup directory is not implemented" | mail -s "$server: Postgres scheduled backup failed" $mailto ; exit 1 ; }
+
 [ ! -d `dirname $mutex` ] && handler mkdir -p `dirname $mutex`
 
 while [ -f $mutex ]; do
@@ -62,37 +66,29 @@ done
 
 start=`date +%s`
 
-echo "nightly $$" > $mutex
+echo "scheduled $$" > $mutex
 
-# remove oldest backup
-if [ -d $older ]; then
-    handler rm -rf $older
+if [ ! "$dir_is_remote" ]; then
+    # move previous backup
+    if [ -d $dir -a $rotate = "True" ]; then
+        handler mv $dir {{ postgresql_backup_dir }}/`date -u +%Y%m%dT%H%M%SZ`
+    fi
 fi
-
-# move old backup to older backup
-if [ -d $old ]; then
-    handler mv $old $older
-fi
-
-# move current backup to old backup
-if [ -d $dir ]; then
-    handler mv $dir $old
-fi
-
-# set up new directory
-handler mkdir -p $dir
 
 # tell postgres we'll be backing up
 psql_handler "SELECT pg_start_backup('$dir');"
 backup_started=1
 
+# ensure the local wal/ directory exists, so rsync creates it for wal archival
+handler mkdir -p $data/wal
+
 # begin the backup
-handler rsync -a --exclude pg_xlog $data/ $dir
+handler rsync $remote_rsync -rptg --delete --delete-delay --exclude pg_xlog $data/ $dir
 
 # tell postgres we're done
 psql_handler "SELECT pg_stop_backup();"
 
-echo "Elapsed time: $(( `date +%s` - $start )) seconds" | mail -s "$server: Postgres nightly backup succeeded" $mailto
+echo "Elapsed time: $(( `date +%s` - $start )) seconds" | mail -s "$server: Postgres scheduled backup succeeded" $mailto
 
 # exit normally
 rm -f $mutex
